// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVs2AQIkLKAezk-0iP9NMngomSr9FLIg',
    appId: '1:312381412536:web:ad40e7b5e03fc1879f904d',
    messagingSenderId: '312381412536',
    projectId: 'jibber-6deca',
    authDomain: 'jibber-6deca.firebaseapp.com',
    storageBucket: 'jibber-6deca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4hY6QZ-Lh2IERbpnKjVDgzFTD9TelgU',
    appId: '1:312381412536:android:2fd7d34bdc48879e9f904d',
    messagingSenderId: '312381412536',
    projectId: 'jibber-6deca',
    storageBucket: 'jibber-6deca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPJK8Djsz9RF--qb3C4n-b_h5t_tWZOI',
    appId: '1:312381412536:ios:c7e741dd030fa5309f904d',
    messagingSenderId: '312381412536',
    projectId: 'jibber-6deca',
    storageBucket: 'jibber-6deca.firebasestorage.app',
    iosBundleId: 'com.example.jibber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZPJK8Djsz9RF--qb3C4n-b_h5t_tWZOI',
    appId: '1:312381412536:ios:c7e741dd030fa5309f904d',
    messagingSenderId: '312381412536',
    projectId: 'jibber-6deca',
    storageBucket: 'jibber-6deca.firebasestorage.app',
    iosBundleId: 'com.example.jibber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzVs2AQIkLKAezk-0iP9NMngomSr9FLIg',
    appId: '1:312381412536:web:32a96e6b745632a49f904d',
    messagingSenderId: '312381412536',
    projectId: 'jibber-6deca',
    authDomain: 'jibber-6deca.firebaseapp.com',
    storageBucket: 'jibber-6deca.firebasestorage.app',
  );
}
